function comment = createHeaderComment
	timestamp = datestr(now);
	% username = getenv('username');
	username = 'NK';
	lineStr = repmat('%',1,35);
	v=ver('MATLAB');
	comment = sprintf(...
		['%s\n' ...
		'%% Created: %s\n' ...
		'%% Computer:  %s\n' ...
		'%% Matlab:  %s\n' ...
		'%% Author:  %s\n' ...
		'%s\n'], ...
		lineStr, timestamp, computer, v.Version, username, lineStr);
end  % createHeaderComment